from transitions import t_atualiza_pfidelidade
from transitions import t_emitir_notificacao_envio
from transitions import t_enviar_produtos
from transitions import t_fechar_pedido
from transitions import t_processar_pagamento
from transitions import t_reserva_produtos
from transitions import t_validar_dados